Added exit status checking and showing an error message if the wrong time format is inserted to ensure the proper time is added. Commit is not made properly until you do this

diff --git a/templates/hooks/commit-msg b/templates/hooks/commit-msg
--- a/templates/hooks/commit-msg
+++ b/templates/hooks/commit-msg
@@ -23,7 +23,19 @@ runGitCommitMsg() {
 }
 
 compileGitCommitMsg() {
-  javac "$SOURCE_DIR"/GitCommitMsg.java
+    javac "$SOURCE_DIR"/GitCommitMsg.java
+}
+
+exitStatus() {
+    if [ $1 -eq 1 ]; then
+        echo "You have entered an invalid time string.\n\n"
+        echo "Please make sure that there is only one space between 'work' and the time.\n\n"
+        echo "Please also make sure the time is formatted properly and goes Days Hours Minutes.\n\n"
+        echo "You do not have to add days or hours if you haven't spent that long on them, but you cannot add days after hours or hours after minutes.\n\n"
+        exit 1
+    else
+        exit 0
+    fi
 }
 
   if [ ! which java >/dev/null 2>&1 ]; then
@@ -38,11 +50,12 @@ compileGitCommitMsg() {
 
   if [ -e "$SOURCE_DIR"/GitCommitMsg.class ];then
       runGitCommitMsg > "$1"
-      exit 0
+      exitStatus $?
+
   else
-      compileGitCommitMsg
+      compileGitCommitMsg # Compile the java file since it isn't compiled or doens't exist
       runGitCommitMsg > "$1"
-      exit 0
+      exitStatus $?
   fi
 
 exit 255 # Exiting abnormally. Shouldn't be here as we exit in the above statements
